### ISSUE TITLE
can we integrate the angular elements lib with react app

### ISSUE THREAD

**Issue by saurabhchavan** [nrwl/upgrade-with-elements#1]

**Comment by thelgevold** [comment]
Yes, elements are platform agnostic, so integration with React or any other framework will work just fine.

**Comment by saurabhchavan** [comment]
thanks. 
I had to switch the build architecture in angular.json for library from 
`       "builder": "@angular-devkit/build-ng-packagr:build",`
to 
`         "builder": "@angular-devkit/build-angular:browser",`
to correctly build a library.
